# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1crJ2H-fpOX8r5KuKhZgQGEdt2Pl90_IX

Using Afinn
"""



from afinn import Afinn

afinn = Afinn()

def get_sentiment(text):
    score = afinn.score(text)
    if score > 0:
        return 'positive'
    elif score < 0:
        return 'negative'
    else:
        return 'neutral'

new_statements = [
    "I am very happy with the service.",
    "This is the worst experience ever.",
    "I am confident",
]

for statement in new_statements:
    sentiment = get_sentiment(statement)
    print(f"statement: {statement} | sentiment: {sentiment}")

